<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <AssemblyName>NonSingletonFileLogger</AssemblyName>
        <RootNamespace>NonSingletonFileLogger</RootNamespace>
    </PropertyGroup>

</Project>
